[project]
name = "chbh-cli"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "scipy",
    "ipython",
    # Visualisation
    "matplotlib",
    "pyside6<6.9",
    # Stats
    "scikit-learn",
    "pandas",
    "polars",
]

[dependency-groups]

meeg = [
    "mne",
    "mne-bids",
    "mne-connectivity",
    "neurokit2",
    "specparam",
    "sails",
]

mri = [
    "nibabel",
    "nilearn",
    "dipy",
    "templateflow",
]

sleep = [
    "yasa",
]

dev = [
    "pytest",
    "ruff",
    "setuptools>=41.0.1",
    "build",
    "pytest",
    "pytest-cov", 
    "coverage",
    "flake8",
    "codespell",
    "twine"
]
